import HonorsBand2425 from "../../assets/Musicians/HonorsBand2425.jpg";
import { AboutProgramCardProps } from "../../Components/AboutProgramCard/types";

export const henryPreviousBandInfo: AboutProgramCardProps = {
  programName: "2024-2025 Henry Honors Band",
  programInfo: `Thank you! Your contributions to our program continue to shine through the band program in so many ways. Your hard work and dedication were the impetus for this performance today. We miss you!`,
  imgSrc: HonorsBand2425,
  roster: [
    "Aaron Louis Alburo",
    "Andrew Allen",
    "Tyler Brode",
    "Colton Brooks",
    "Noelani Burt",
    "Valeria Zambrano Ceniceros",
    "Kalista Choy",
    "Seongyeon Chung",
    "Chloe Cross",
    "Liam Cruz",
    "Jameson Fort",
    "Leo Gangatirkar",
    "Ellie Garcia",
    "Sonya Gebhardt",
    "William Geiger",
    "Jeremy George",
    "Teller George",
    "Charlotte Hall",
    "Emily Harrison",
    "Seojun Hong",
    "Anne Homerstad",
    "Justin Howard",
    "Coa Huynh",
    "Audrey Ivy",
    "Ethan James",
    "Leo Jeong",
    "Levin Jeong",
    "Seungjun Kim",
    "Suhyun Kim",
    "Lidziya Krutsko",
    "Thisal Kularatne",
    "Nathan Kunitz",
    "Ian Leandro",
    "Kanghoon Lee",
    "Nikki Lefebvre",
    "Emilie Leung",
    "Yu-Tsen Lin",
    "Mason Maginel",
    "Miah Mendez",
    "Hayden Murphy",
    "Brayley Nelson",
    "Yohan Pak",
    "Jiwoo Park",
    "Seoin Park",
    "Sieon Park",
    "Dyllan Rauda",
    "Owen Resendiz",
    "Carla Galarza Rizzo",
    "Jeremiah Roberts",
    "Denae Rosario",
    "Johan Samuel",
    "Riaan Shah",
    "Aiden Sharma",
    "Sawyer Shoup",
    "Arunav Tanguturi",
    "Aarush Thakkar",
    "Riley Tillerson",
    "Amani Tyagi",
    "Ava Uppayokhin",
    "Samiksha Vageeswaran",
    "Walter Wingate",
  ],
};
